name: Functional Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: 0.5.24
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"

    - name: Install the project
      run: uv sync --all-extras --dev

    - name: Run tests
      run: |
        docker network create net-test
        uv run pytest
      env:
        CROWDSEC_TEST_TIMEOUT: 60

    - name: Lint
      run: |
        uv run ruff check
        uv run basedpyright

